"""
1. Pull total number of sales that were completed on 18th March 2023
2. Pull total number of sales that were completed on 18th March 2023 with the first name ‘John’ and last name ‘Doe’
3. Pull total number of customers that purchased in January 2023 and the average amount spend per customer
4. Pull the departments that generated less than $600 in 2022
5. What is the most and least revenue we have generated by an order
6. What were the sales that were purchased in our most lucrative order
"""

--Question 1
SELECT count(*)
FROM sales
WHERE date == "03-18-2023"

--Question 2
SELECT count(*)
FROM sales,customers
WHERE sales.customer_id = customers.customer_id AND 
        date = "03-18-2023" AND 
        customers.first_name = "John" AND 
        customers.last_name = "Doe"

--Question 3
SELECT count(*) as "Total Number of Customers in January 2023" , avg(total_rev_by_cust) as "Avg Amnt Spent per Customer"
FROM (
  SELECT customers.customer_id, sum(amount) as total_rev_by_cust
  FROM customers,sales 
  WHERE customers.customer_id = sales.customer_id AND 
        date between "01-01-2023" AND "01-31-2023"
  GROUP BY customers.customer_id)

--Question 4
SELECT department, sum(sales.revenue) as rev
FROM sales,items
WHERE items.item_id == sales.item_id AND
        date between "01-01-2022" AND "12-31-2022"
GROUP BY department
HAVING rev < 600

--Question 5
SELECT max(revenue),min(revenue)
FROM sales

--Question 6
SELECT order_id, sum(revenue) as rev
FROM sales
GROUP BY order_id
HAVING rev >= (
    SELECT max(revenue)
    FROM sales
    GROUP BY order_id
)